### ISSUE TITLE
Cutting a new release?

### ISSUE THREAD

**Issue by danielcompton** [ninjudd/clojure-complete#22]
Are you able to cut a new release of this to include https://github.com/ninjudd/clojure-complete/pull/20?

**Comment by trptcolin** [comment]
Sorry, looks like I [released 0.2.4 in 2014](https://clojars.org/clojure-complete/versions/0.2.4) but never pushed the commits or tags to Github, or updated the issues. My bad. `[clojure-complete "0.2.4"]` exists.
