### ISSUE TITLE
java.ext.dirs is deprecated

### ISSUE THREAD

**Issue by pcn** [ninjudd/clojure-complete#23]
So in ubuntu xenial, using openjdk 9, it seems like java.ext.dirs isn't present.  This may be due to a change in the structure of how java is distributed/runs according to http://openjdk.java.net/jeps/220.  In any case, the behaviour I'm getting when trying to use repl completion is this:

https://gist.github.com/pcn/6272f116e6884728a66a

It was suggested in IRC that this is the root of the problem:

https://github.com/ninjudd/clojure-complete/blob/09827b3db506126e6445bd87384b34776a94741e/src/complete/core.clj#L66

I'm not sure what an appropriate fix would be, but I'm reporting this in the hope that it helps.

**Comment by venantius** [comment]
I believe this was resolved by #25
